/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxinteg.h
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  June 5, 2024
 *  time:  1:57:20 PM
 *  user:  Universiteit Twente
 *  from:  -
 *  build: 5.1.1.13146
 **********************************************************/

/* This file describes the integration methods
that are supplied for computation.

   Currently the following methods are supported:
   * Euler
   * RungeKutta2
   * RungeKutta4
   but it is easy for the user to add their own
   integration methods with these two as an example.
*/

#ifndef XX_INTEG_H
#define XX_INTEG_H

/* 20-sim include files */
#include "xxtypes.h"

/* the chosen integration method */
#define Discrete_METHOD

/* the integration methods */
void XXDiscreteInitialize (void);
void XXDiscreteTerminate (void);
void XXDiscreteStep (void);

extern XXBoolean xx_major;

#endif

