/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxmatrix.h
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  June 5, 2024
 *  time:  1:57:20 PM
 *  user:  Universiteit Twente
 *  from:  -
 *  build: 5.1.1.13146
 **********************************************************/
/* Empty file, no matrix support functions are needed for this model */


