#ifndef _ALTERA_HPS_0_BRIDGES_H_
#define _ALTERA_HPS_0_BRIDGES_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file 'soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0_bridges' and devices
 * connected to the following masters:
 *   axi_f2h
 *   h2f_lw
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'esl_bus_demo_0', class 'esl_bus_demo'
 * The macros are prefixed with 'ESL_BUS_DEMO_0_'.
 * The prefix is the slave descriptor.
 */
#define ESL_BUS_DEMO_0_COMPONENT_TYPE esl_bus_demo
#define ESL_BUS_DEMO_0_COMPONENT_NAME esl_bus_demo_0
#define ESL_BUS_DEMO_0_BASE 0x0
#define ESL_BUS_DEMO_0_SPAN 1024
#define ESL_BUS_DEMO_0_END 0x3ff


#endif /* _ALTERA_HPS_0_BRIDGES_H_ */
