/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.h
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  June 7, 2024
 *  time:  10:50:33 AM
 *  user:  Universiteit Twente
 *  from:  -
 *  build: 5.1.1.13146
 **********************************************************/

/* This file defines the functions necessary for motion profiles
   functions
*/
